#!/usr/bin/env ruby

require 'telemetry/logger'
require 'telemetry/scriber'

trap('SIGTERM') { @quit = true }
trap('SIGHUP') { @quit = true }
trap('SIGINT') { @quit = true }

Telemetry::Scriber.bootstrap
Telemetry::Scriber.start_reader

@quit = false

until @quit
  begin
    sleep(0.1) unless Telemetry::Scriber.flush
  rescue StandardError => e
    Telemetry::Logger.error "#{e.class}: #{e.message}"
    Telemetry::Logger.error e.backtrace
    sleep 1
  end
end

Telemetry::Scriber.stop
